name: Django-Workflow


on:
  push:
    branches:
      - django-project


jobs:
 run_tests:
   runs-on: [ubuntu-latest]

  steps:
   - uses: actions/checkout@django-project

   - uses: actions/setup-python@v1
     with:
       python-version: '3.8'
       architecture: 'x64'

   - name: Install requirements
     run: pip install -r requirements.txt

   - name: Run tests
     run: pytest --cov
#   - name: Tests report
#     run: coverage report