name: Publish on Docker Hub and Deploy

on:
  push:
    branches:
    - django-project

jobs:
  build-push-image:
    name: Build and Push Docker images
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Run tests
      run: |
        docker build ./lab3/education -t dariwes/django_project_prod:v1.0 -f ./lab3/education/Dockerfile.prod
        docker build ./lab3/nginx -t dariwes/nginx_project:v1.0 -f ./lab3/nginx/Dockerfile
        docker-compose -f ./lab3/docker-compose.prod.yml up -d
        docker exec django-web pytest
        docker-compose -f ./lab3/docker-compose.prod.yml down
    - name: Push to Docker Hub
      run: |
        docker push dariwes/django_project_prod:v1.0
        docker push dariwes/nginx_project:v1.0

  deploy:
    runs-on: [ubuntu-latest]
    needs: [build-push-image]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Reload Project
        run: gcloud compute ssh supersonic@django-project --zone=us-central1-a --command="sudo sh app/Programming-Tools-and-Utilities/lab3/run.sh prod"
