name: Docker-Siries-Builds

on:
  push:
    branches:
    - django-project

jobs:
  build-images:
    name: Build and push docker images
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build education
      run: |
        docker build ./lab3/education -t dariwes/django-project:latest  -f ./lab3/education/Dockerfile
    - name: Push to docker hub
      run: |
        docker push dariwes/django-project:latest
