name: Docker-Siries-Builds

on:
  push:
    branches:
    - django-project

jobs:
  build-push-image:
    name: Build and push docker images
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and run tests
      run: |
        docker build ./lab3/education -t dariwes/django_project_prod:latest  -f ./lab3/education/Dockerfile.prod
        docker build ./lab3/nginx -t dariwes/nginx_project:latest  -f ./lab3/nginx/Dockerfile
        docker-compose -f ./lab3/docker-compose.prod.yml up -d
        docker ps -a
        docker exec django-web pytest
        docker-compose -f ./lab3/docker-compose.prod.yml down
    - name: Push to docker hub
      run: |
        docker push dariwes/django_project_prod:latest
        docker push dariwes/nginx_project:latest

