name: Docker-Siries-Builds

on:
  push:
    branches:
    - django-project

jobs:
  build-images:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_USER $DOCKER_PASSWORD"
        echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USER --password-stdin
    - name: docker build education
      run: |
        docker build ./lab3/education -f Dockerfile -t $DOCKER_USER/django-project:1.0.0
    - name: docker push
      run: |
        docker push $DOCKER_USER/django-project:1.0.0
