name: Docker-Siries-Builds

on:
  push:
    branches:
    - django-project

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: docker build django
      run: |
        docker build ./lab3/education -t dariwes/django-project:1.0.0
